[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[[constraint]]
  name = "github.com/onego-project/onego"
  version = "1.1.0"

[[constraint]]
  name = "github.com/remeh/sizedwaitgroup"
  branch = "master"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.4.1"

[[constraint]]
  name = "github.com/beevik/guid"
  branch = "master"

[[constraint]]
  name = "github.com/karrick/tparse"
  version = "v2.6.1"

[[constraint]]
  name = "github.com/rafaeljesus/retry-go"
  version = "1.0.0"

[[constraint]]
  name = "github.com/goat-project/goat-proto-go"
  branch = "master"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "v1.3.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "v1.19.1"

[[constraint]]
  name = "github.com/dnaeon/go-vcr"
  version = "v1.0.1 "

[[constraint]]
  name = "github.com/google/uuid"
  version = "v1.1.1"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "v1.10.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "v1.7.0"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  name = "cloud.google.com/go"
  version = "v0.44.3"