# Configuration file for Goat-one - GO Accounting Tool for OpenNebula.

# Flags are set via this configuration file or from command line flags.
# Settings from command line flags replace configuration settings.

# Identifier of an instance (required)
identifier: goat

# The records are filtered by time. Filter allows the records
# from time, to time or for a period. It cannot filter
# the records from/to and records for a period in the same time.
# Time from and time to can be used independently.
# Time from has to be earlier than time to.
# Time settings or period setting are optional, the default filter
# uses time from 0000-00-00 00:00:00 to current time (now).

# Records from given time (optional)
# time format: yyyy-mm-dd hh:mm:ss + nsec nanoseconds
records-from:

# Records to given time (optional)
# time format: yyyy-mm-dd hh:mm:ss + nsec nanoseconds
records-to:

# Records for given period (optional)
# The following tokens may be used to specify the respective unit of time:
# Nanosecond: ns
# Microsecond: us, µs (U+00B5 = micro symbol), μs (U+03BC = Greek letter mu)
# Millisecond: ms
# Second: s, sec, second, seconds
# Minute: m, min, minute, minutes
# Hour: h, hr, hour, hours
# Day: d, day, days
# Week: w, wk, week, weeks
# Month: mo, mon, month, months
# Year: y, yr, year, years
records-for-period: 2w

# Goat server endpoint (required)
# Required format is hostname:port
endpoint: 127.0.0.1

# OpenNebula endpoint (required)
# Required format is hostname:port
opennebula-endpoint: 127.0.0.1

# OpenNebula secret (required)
# Required format is username:password
opennebula-secret: oneadmin:123456

# Timeout for OpenNebula calls (required)
opennebula-timeout: 5m

# Debug mode (true/false)
debug: false

# Path to log file (optional)
log-path:

# The following commands are specific for given resources.

# Subcommands specific for a virtual machine.
vm:
  # Site name (required)
  site-name: goat-vm-site-name

  # Cloud type (required)
  cloud-type: goat-vm-cloud-type

  # Cloud compute service (optional)
  cloud-compute-service:

# Subcommands specific for a network.
network:
  # Site name (required)
  site-name: goat-network-site-name

  # Cloud type (required)
  cloud-type: goat-network-cloud-type

  # Cloud compute service (optional)
  cloud-compute-service:

# Subcommands specific for a storage.
storage:
  # Site (optional)
  site: